### ISSUE TITLE
Domain amazon.com does not match reported account domain https://www.amazon.co.uk; functionality is not likely to work, please fix

### ISSUE THREAD

**Issue by danmed** [custom-components/alexa_media_player#1129]
I'm running this as an integration through HACS on HA OS.. .everything seems to be working but this log annoys me...

How do i fix it?

**Comment by alandtse** [comment]
Register devices to your domain properly. I get too many people saying stuff doesn't work because they chose the wrong domain. This is intended to stop that.

**Comment by danmed** [comment]
Sorry, I'm confused.. Can you explain exactly what I've done wrong?

**Comment by alandtse** [comment]
If everything is working, then just ignore the warning. But you should make sure your Amazon account is registered to the domain you're using. If not, you can [change](https://www.amazon.com/gp/help/customer/display.html/ref=hp_left_v4_sib?ie=UTF8&nodeId=201248840) it. And that devices are also [registered](https://www.bestusefultips.com/how-to-change-alexa-location-country-in-alexa-app/) in the right domain.

But again, if it works for you, I wouldn't change anything.

**Comment by michthom** [comment]
I apologise if I'm necroposting, but I've also run into this issue (in a fresh install of alexa_media_player 3.6.3) and my amazon.co.uk account shows my country/region set correctly to "United Kingdom" and I can see all my devices both in Amazon's "Devices" tab and also in the HA media_player list now, but I can't communicate with them, getting the same error as the OP above. In my logs I can see:

2021-02-01 00:00:33 DEBUG (MainThread) [alexapy.alexalogin] Login created for ****my_email**** - amazon.com

Does this mean that I somehow messed up the app setup on the Amazon site? The documentation links to the amazon.com domain to generate the 2FA key. but I thought I should log in to the UK site instead (https://www.amazon.co.uk/a/settings/approval), which is where I got my built-in 2FA key, which successfully worked when configuring the custom component? But that doesn't seem to have configured the media_player for my region.

I didn't see any instructions in the installation guide on how to set a non-US region, but if they exist please point me to them?

**Comment by michthom** [comment]
Yup - I was a buffoon (and @danmed you may have done what I did also). When adding the integration into HA, you need to change amazon.com if that's not your region to amazon.co.uk or whatever. I completely missed that step, but after removing and reinstating the component, it all works just fine.

**Comment by garethcheyne** [comment]
Just want to add comment to this, and believe that making the changes solved all my problem.

Preamble, originally when I got my first echo, years ago AU/NZ was not a region, and there for set up in US. Following @alandtse instruction above, I changes my region, de-register all my devices, and then re-registered them again. Now everything is working as expected.

After first install I managed to send a few tts commands, and work, and then it just all turned to crap. I also noticed in my network I was getting flood traffic out of my echo devices to the point that my firewall start dropping the packets.  Since I have done the above, and reset it all back up, iIno longer have this issue, I can send tts, media_play commands etc, and my Echo stay online.

@alandtse Amazing, this is working wonders, and be good in the future to send media_play commands, to a echo smart group.  This is really going to help with my new home that we are building, and having Home Assistant, and Echo drive everything.
 5* addon.

**Comment by adwoodworth** [comment]
I'll just add that it is a little bit awkward for people who move devices around countries and have multiple accounts.  Seems like the error handling or logging should consider this.  I can't just unregister and reregister devices on a frequent basis.  Everything seems to work OK, but the entry in the log persists.

**Comment by alandtse** [comment]
Thanks. Given this misconfiguration is the cause for a lot of broken functionality, it'd be hard to remove it. There's no way to know it's someone with the special use case of moving countries. Just ignore it if you're in that special case.

**Comment by Sonnenwerk** [comment]
Instead of starting from scratch..is there a way to edit a HA file to change the region too ?

**Comment by danielbrunt57** [comment]
> Instead of starting from scratch..is there a way to edit a HA file to change the region too ?

It only takes about a minute for me to re  & re the integration. but if you prefer editing a system critical file, it's inside `/config/.storage/core.config_entries`.  Just don't mess it up or you'll end up spending far more time fixing the botch than doing a re & re...
