### ISSUE TITLE
Thousands of A records queries

### ISSUE THREAD

**Issue by timaseth** [custom-components/alexa_media_player#1176]
I have a pi4 with Pi-Hole as a host-network docker container. Everything was well until last week when I saw hundreds of thousands of hits to `alexa.amazon.in`
They originate not from any Amazon devices but from HA and the Alexa Media player is the only suspect. When I Stop the HA container and reboot the pi; the messages stop.
Simple A and AAAA record queries, one every second.
After flushing the query log, this is the first query
![image](https://user-images.githubusercontent.com/60132339/107196740-02490a80-6a19-11eb-9a81-8bf10df3e18c.png)
followed by thousands of these..
![image](https://user-images.githubusercontent.com/60132339/107196778-10972680-6a19-11eb-80df-863cbf8b5a37.png)

On a lark, I used the Local DNS Setting of Pi-Hole and added a faux IP to alexa.amazon.in
Of course the said add-on no longer works in this case but the stream of messages instantly stopped.

I put this issue up up on the pihole forum and this is what I got:
_" Suppose it is time to raise an issue with the developers of the Alexa component that their app is not cacheing the DNS resolve correctly. I assume they didn't even think about doing this and just rely on the operating system doing it for them (which a Raspberry Pi won't do by default, but others, like Ubuntu actually do it). So it's likely they just missed this entirely. Please do report this and keep this in mind. They are likely not even aware of it."_

I am typing this from my workplace why unable to share HA and MP details but basically:
HA Containerised (latest on 07 Feb 21) on a Raspberry pi4/4GB with Raspberry Pi OS updated on 08 Feb 21.
Alexa Media player reinstalled on 07 Feb 21. Pi hole latest on 07 Feb 21.

**Comment by alandtse** [comment]
First, I'm not sure what the ultimate issue is. Your pi.hole is caching the DNS requests so it's only something happening within your network. Are you seeing some performance degradation or any ill effects? For the record, the component relies on [aiohttp's](https://docs.aiohttp.org/en/stable/client_advanced.html#tuning-the-dns-cache) native caching of 10 seconds. But I don't think that's the issue.

Second, I'm not sure it's the component doing hundreds of thousands of hits. We keep a metric of api calls so if you use the force_logout service, it will tell you how many api calls it has done since the last login/restart. I would be very surprised to see it too high. You can turn on logs on alexapy and also see how many calls the device is making.

I just checked my pihole and in the last 24 hours, my 7 echo devices have only made 255 dns queries to an amazon.com domain. If you're seeing 100,000s of hits, I suspect you may have some sort of dns reflection set up in your network that can happen with [conditional forwarding](https://discourse.pi-hole.net/t/too-many-queries-made-when-conditional-forwarding-is-enabled/11828) or some other cause.

Go ahead and try the following:

1. Force a log out and see how many API calls it's had since login/reboot.
2. Disable the component for a day and see if the calls are still prevalent.
3. Look at your alexapy logs and see what is causing it to make calls.

**Comment by alandtse** [comment]
Actually ignore my stats. My HA isn't behind the pihole right now. But please do the other things I mentioned.

**Comment by timaseth** [comment]
> Go ahead and try the following:
> 
> 1. Force a log out and see how many API calls it's had since login/reboot.
> 2. Disable the component for a day and see if the calls are still prevalent.
> 3. Look at your alexapy logs and see what is causing it to make calls.
Thanks for your reply - I am new to this and not sure of the steps to go about doing the above tasks. I know it is a chore and appreciate your time but whenever you can spare a few minutes, please guide.
