### ISSUE TITLE
Rename Brazilian Portuguese Translation

### ISSUE THREAD

**Issue by LeandroIssa** [custom-components/alexa_media_player#1526]
I would like to ask to rename the translation files. The correct one for the Brazilian Portuguese translation to be applied is pt-BR, not pt_BR as it is in the component. The correct one for the portuguese version of Portugal is just pt and not pt_PT as it is in the component.

![Captura de tela 2022-03-02 164958](https://user-images.githubusercontent.com/67451572/156439115-ab21d77e-d16d-485a-b3b1-6bcc1dccd0d7.png)

With the renamed file the translation is applied.

![Captura de tela 2022-03-02 165125](https://user-images.githubusercontent.com/67451572/156439118-99e6a60a-8e02-4609-8cf5-6141cb99cee4.png)

Thanks for listening.

**Comment by alandtse** [comment]
Translations are handled here. https://github.com/custom-components/alexa_media_player/wiki/Translations

**Comment by w35l3y** [comment]
https://github.com/custom-components/alexa_media_player/blob/a27ee46b1f68628d39b80a5db41e2f7d377c165e/.github/workflows/semantic_release.yml#L25

Probably, adding `          --bundle-structure "locale/%LANG_ISO%.json" \` could fix it.
I am not sure because I don't know how to execute that command to download the files locally.

| Expected (as stated in the docs) | Actual |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/963510/156698323-30188f0a-19f7-4628-bbfd-0928722cccb4.png) | ![image](https://user-images.githubusercontent.com/963510/156698443-cceb5680-2eeb-4543-9daa-ff92e018f62b.png) |
|| There isn't any option to download the files in the actual view. |

For details:
* https://docs.lokalise.com/en/articles/3150682-downloading-translation-files
* https://docs.lokalise.com/en/articles/2281317-filenames#example-1-single-file-per-language

The other option could be made in the `Language Settings` at Lokalise, but we can't modify it, only the owner of the project can.

| Expected (as stated in the docs) | Actual |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/963510/156698737-89ee573c-3ac9-40c9-9a55-6c54d1b196a1.png) | ![image](https://user-images.githubusercontent.com/963510/156698834-62cfe1ca-72ea-434a-bc76-5c5725fec352.png) |
|| There isn't any Language Settings in the actual view. |

For details:
* https://docs.lokalise.com/en/articles/1400544-language-settings

**Comment by w35l3y** [comment]
I just tested using REST but it returns forbidden.
And yes, I created an API token.
```
REQUEST
curl --location --request POST 'https://api.lokalise.com/api2/projects/465185555eee18dd537ca6.39714580/files/download' \
--header 'X-Api-Token: ...' \
--header 'Content-Type: application/json' \
--data-raw '{
    "format": "json",
    "original_filenames": false
}'

RESPONSE
{
    "error": {
        "message": "Forbidden",
        "code": 403
    }
}
```
For details:
* https://app.lokalise.com/api2docs/curl/#transition-download-files-post
* https://app.lokalise.com/profile#apitokens
