### ISSUE TITLE
Invalid Built-In 2FA key

### ISSUE THREAD

**Issue by nmsoares** [custom-components/alexa_media_player#1617]
Hi,
after updating to the latest version I cannot authenticate !
Allways get "Invalid Built-In 2FA key" when putting in the correct code from the APP.

**Comment by Pacococo** [comment]
> Hola, después de actualizar a la última versión no puedo autenticarme! Siempre obtiene "Clave 2FA incorporada no válida" al ingresar el código correcto de la APLICACIÓN.

Me ocurre lo mismo y no sé qué puedo hacer

**Comment by jouster1974** [comment]
same here...multiple attempts same issue

**Comment by alandtse** [comment]
That field isn't for the OTP, it's for if you're registering a 2FA app. https://github.com/custom-components/alexa_media_player/wiki/Configuration#built-in-2fa-app

**Comment by charettepa** [comment]
this new method only works when you change from the default https to http and use ip address
if you leave it as https with ddns address it fails to proceed
my htps address is acessible externaly by ddns using the NGINX Home Assistant SSL proxy and i forward the 443 port
do you require any other ports forwarded for this to work?

also it wants to resetup at every reboot of the system
at which time its trying to use https again

**Comment by charettepa** [comment]
no, there is a built in authenticator app
since v4 you can only use that

however there seems to be an issue
it insists on authenticating using https
which is acessible and has a valid cert
but will not proceed even though everything is correct
changing it to http and using port 8123 seems to make it authenticate
but at every reboot the issue returns, even though remember was selected
i thinnk its because after a reboot it seems to want to revert to the ddns on https
which for some reaon is not working despite having https with ddns and cert working corectly

**Comment by alandtse** [comment]
> it insists on authenticating using https
> which is acessible and has a valid cert
> but will not proceed even though everything is correct
> changing it to http and using port 8123 seems to make it authenticate
> but at every reboot the issue returns, even though remember was selected
> i thinnk its because after a reboot it seems to want to revert to the ddns on https
> which for some reaon is not working despite having https with ddns and cert working corectly

Your issue is unrelated to this topic, `Invalid Built-In 2FA key`. I will be marking further discussion on the proxy url as offtopic.

As for your proxy url issue, please search as it has been discussed before. The HA component will check if the provided URL is accessible from the HA server using a simple get to the url. If it can't connect, it reports an error. For some reason, it can't connect to your external address; check your network settings.  The proxy url isn't used to communicate with Amazon at all so has no bearing on reboots. 

As of 4.0.x, the component will force a reauth if it detects you have a degraded connection to Amazon (e.g., the mac_dms token is not provided by Amazon disabling websockets). I can't control when Amazon wants to provide it to you. You can downgrade to the 3.x series if this behavior doesn't work for you.

**Comment by nmsoares** [comment]
I FINALLY got it !!! This is not well explained at all!!! C'mon ....
it's so simple ... 
1º - go to [Amazon.com's 2FA page](https://www.amazon.com/a/settings/approval)
2º - IGNORE the QR code and link on "Can't scan the barcode"
3º - Copy the string presented 
4º - Paste the string in the Built-in 2FA back in Home Assistant

no problems with https whatsoever.

Thanks @charettepa for the help and please just put it back in a simple way because everyone is mislead to use the 2FA Code from an Authenticator app.

**Comment by charettepa** [comment]
@nmsoares 

nope requires resetting up using the long key at every single reboot

i have spent all day on this
the old method worked just fine and never needed re-setting up
just a new 2fa code once in a blue moon

i think its because the connection comes technically from your browser and not HA, unlike the previous method
therefore when HA reconnects Amazon sees it as a new connection thats not "remembered"
so it wants you to reauthenticate

the dev suggested to use to old 3.x method
but what will happen when 3.x dosent work anymore

there has to be a more graceful way to handle this
either a method to store the cookie or a way for the browser launch to be from HA itsself so it can be reembered

**Comment by charettepa** [comment]
> As of 4.0.x, the component will force a reauth if it detects you have a degraded connection to Amazon (e.g., the mac_dms token is not provided by Amazon disabling websockets). I can't control when Amazon wants to provide it to you. You can downgrade to the 3.x series if this behavior doesn't work for you.

is there not a way to just use the normal login method that has always worked?
because of the way its done, in your own browser, the connection will always be "degraded" on reboot
the cookie for the session simply will not exist in HA unless you offer a way to import it like google maps integration does

**Comment by nmsoares** [comment]
@charettepa let me know how to help.

**Comment by charettepa** [comment]
@alandtse 

neither one of my last 2 coments were regarding proxy
they were regarding this new authentication method with issue for "Built-In 2FA key"
why were they flagged off topic?

one of them was a direct answer to someone else who thanked me for assisting

**Comment by alandtse** [comment]
The topic is `Invalid Built-In 2FA key`. References to issues with needing to reauth on reboot are not related to this topic.

**Comment by charettepa** [comment]
> @charettepa let me know how to help.

@nmsoares 

looks like @alandtse wants a new issue created for "reauth on reboot"

**Comment by yurbd** [comment]
> I FINALLY got it !!! This is not well explained at all!!! C'mon .... it's so simple ... 1º - go to [Amazon.com's 2FA page](https://www.amazon.com/a/settings/approval) 2º - IGNORE the QR code and link on "Can't scan the barcode" 3º - Copy the string presented 4º - Paste the string in the Built-in 2FA back in Home Assistant
> 
> problems restarting where it requires new Authentication.....
> 
> Thanks @charettepa for the help I was mislead to use the 2FA Code from an Authenticator app!
> 
> How is the reauthentication after reboot fixed ???

OMG Thanks, i would never figure this out, they should explain

**Comment by Albruaje** [comment]
> I FINALLY got it !!! This is not well explained at all!!! C'mon .... it's so simple ... 1º - go to [Amazon.com's 2FA page](https://www.amazon.com/a/settings/approval) 2º - IGNORE the QR code and link on "Can't scan the barcode" 3º - Copy the string presented 4º - Paste the string in the Built-in 2FA back in Home Assistant
> 
> problems restarting where it requires new Authentication.....
> 
> Thanks @charettepa for the help I was mislead to use the 2FA Code from an Authenticator app!
> 
> How is the reauthentication after reboot fixed ???

Several times tried.....but no success....
