### ISSUE TITLE
TTS option no longer working

### ISSUE THREAD

**Issue by Langtonpaul** [custom-components/alexa_media_player#1636]
Hi Ive had tts working in the past cant get it working now just wandering if anyone else is have same issues, wont work in developer tools services or on Ha cloud page TTS (try it). Incidentally I can get google assistant to work from same try it location. 
Thank you.
Home Assistant Core 2022.6.5
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.1

**Comment by wood-cottage** [comment]
I've just noticed this myself too.
Changing from "TTS" to "announce" got it working again but with the annoying beep before it.

**Comment by markaggar** [comment]
Ditto.  I came here to say this.  It stopped working at least a few days ago for me.

**Comment by noddy119** [comment]
Same issue for me but only on Echo Dot - Echo Show is ok.  Changing from "TTS" to "announce" got it working again as previous post.

**Comment by Tafke** [comment]
I've been using text-to-speech (tts) with Alexa Media Player for over a year without a problem. But a few weeks ago Alexa Media Player stopped working even though I didn't change anything. All Alexa Media Player connected identities are now in "unavailable” status. This is very annoying because I have several automations that no longer work because in them I use tts as a notification service. Anny idea what could be causing this and how to fix it?
I reinstalled the Alexa Media Player integration several times (HACS + standard integration), but this didn't solve the problem.
The oldest full backup I have available dates from June 12th. I don't think a restore of this backup will help either because the problem occurred before.
I always do updates (core and integrations) immediately.

Home Assistant core-2022.6.5
Home Assistant supervisor-2022.05.3
Home Assistant OS 8.2

**Comment by danielccarmo** [comment]
Mine stoped working yesterday. Even announce doesn't work. I am in the same of Tafke

**Comment by alandtse** [comment]
Please fill out the template and provide logs when trying to TTS option.

For those complaining everything is unavailable, you have a different issue. Please ensure you're actually able to log in and open or find an appropriate issue.

**Comment by alandtse** [comment]
Closing in favor of #1649 since there's a response there.
