### ISSUE TITLE
Echo Occupancy/Vacancy

### ISSUE THREAD

**Issue by oneseventhree** [custom-components/alexa_media_player#1664]
Hi,

I just got the 4th Gen Echo that has Occupancy/Vacancy. Is it possible to have a sensor for this in HA? Something like a motion sensor would be great.

Thank you in advance and for a great integration!

**Comment by kmil4** [comment]
You can do this with fairly low effort.
1. Make a Template Light
2. Expose that light to Alexa via Home Assistant Cloud (or otherwise)
3. Go into the Alexa app, and create two routines: (1) to turn on your Template Light when the echo detects occupancy, and (2) to turn it off when not detected

Boom. You now have a signal for "occupied" vs "not" directly on home assistant, and it's actually quite responsive.

**Comment by alandtse** [comment]
The suggested routine is probably the way to do this unless the App exposes the occupancy sensor so we can reach it via the API. I'll leave this open for a little here in case someone does provide info about the API. After that, I'll move this to a discussion and mark the routine as the answer.

**Comment by oneseventhree** [comment]
> You can do this with fairly low effort.
> 
> 1. Make a Template Light
> 2. Expose that light to Alexa via Home Assistant Cloud (or otherwise)
> 3. Go into the Alexa app, and create two routines: (1) to turn on your Template Light when the echo detects occupancy, and (2) to turn it off when not detected
> 
> Boom. You now have a signal for "occupied" vs "not" directly on home assistant, and it's actually quite responsive.

I already have something like this and it hardly works well due to the cool down of the vacancy being so long - I think its over 30 minutes. I was hoping the API could do better and make it more like a motion sensor with a less of a delay

**Comment by alandtse** [comment]
We only have what the App can expose. Do you see motion sensor type data coming from the app? If not, I think you're stuck with an occupancy sensor which is provided by Amazon.
