### ISSUE TITLE
Notifications and custom commands are not waiting until complete before moving on to next sequence

### ISSUE THREAD

**Issue by alexisspencer** [custom-components/alexa_media_player#1669]
**Describe the bug**
Whenever I call either the notify.alexa_media service or send a custom command to Alexa using this app within a script of automation, HA doesn't wait until Alexa has completed the notification / custom command before it moves on to the next sequence in the script

**To Reproduce**
1. Create a script
2. Call the notify.alexa_media service with a long message
3. Call the media_player.volume_set service for the same Alexa device as step 2
4. Run the script
5. Volume will change before the message has been announced

**Expected behavior**
When step 2 occurs, the script should wait for Alexa to complete its announcement before moving on to step 3

**System details**
 - Home-assistant (version): 2022.7.5
 - Hassio (Yes/No): Yes
 - alexa_media  (version from `const.py` or HA startup): 4.0.3
 - alexapy (version from `pip show alexapy` or HA startup): 1.26.1
 - Amazon [2FA is enabled]: yes

**Comment by alandtse** [comment]
This is how Alexa works. There is no way to tell when a command is finished. If you want this behavior, you'll need to use Alexa's built in routines unfortunately.

**Comment by Bachigaloupe** [comment]
> This is how Alexa works. There is no way to tell when a command is finished. If you want this behavior, you'll need to use Alexa's built in routines unfortunately.

I admire your patience alandtse, I wonder if you feel like you are fighting an uphill battle. I follow this because I have an investment in Amazon devices but have pretty much given up on using them even without HA. 

However, once a few things are finished up, I would like to see if I could help by testing scenarios etc. 

I am sorry I am not sure the best way to contact a developer and especially one that was put in a position to defend themselves. Heck GitHub is new and I am probably type and it will say I am not logged in or something. So many new things to learn in HA. 

Let me know if you would like some dialogue and how does one do that in these circles. I thought Discord was for gamers but now I am on that too. All part of the journey!

Well great work alandtse!

**Comment by alexisspencer** [comment]
Just in case anyone else comes across this issue, I've done a bit of additional testing and alandtse's amazing integration has nothing to do with the issue at all.  Its an Amazon-side issue.
It's actually quite specific to the "read today's calendar" and "read tomorrows calendar" commands, and it's actually something that seems to happen specifically on Echo Show 8 and Echo Show 10 devices (at least).
The same issue happens inside the Alexa app if you create a routine for these commands and manually trigger the routine on either of the devices I mentioned.  All other commands are fine, just these two commands..  Its like these two commands when triggered on these two devices specifically don't seem to wait for the command to finish before moving to the next command that is in some sort of "command queue" or whatever its called.
