### ISSUE TITLE
Alexa IAQ Device

### ISSUE THREAD

**Issue by sdaltons1** [custom-components/alexa_media_player#1786]
Hello,

Piggybacking off the closed issue here:

https://github.com/custom-components/alexa_media_player/issues/1641

Would love to see support for the IAQ device added.  

https://www.amazon.com/Introducing-Amazon-Smart-Quality-Monitor/dp/B08W8KS8D3

I am not super tech savvy but if there is anything I can provide from the device to help with this, please let me know.  Thanks!

**Comment by Snid0** [comment]
Same would love to see this. Its a cool device that would be an awsome device if it could play with HA. I am happy to help test if anyone was able to work on this. I would love to have a go at integrating it myself, but lack the skills. If anyone was able to give me a few pointers on where to start, I woiuld give it a go tho!

**Comment by Snid0** [comment]
Just thought I would privide a little update. I have been having a play around with this. Please bear in mind I have zero experience with HA custom comonents or Python for that matter.

I have managed to get the temperature and and IAQ score from the amazon air monitor into HA by playing around with the alexa_media_player code on my installation. I looked at the TemperatureEntity already implemented as the basis for this.

I am confident I can get the other readings into HA, its just a matter of repeating the process for each reading.

The problem is each reading from the meter has the same name and namespace and is only distinguised by an instance number. 

       "capabilityStates":[
            "{\"namespace\":\"Alexa.ToggleController\",\"name\":\"toggleState\",\"instance\":\"11\",\"value\":\"ON\",\"timeOfSample\":\"2022-12-15T19:45:39Z\"}",
            "{\"namespace\":\"Alexa.TemperatureSensor\",\"name\":\"temperature\",\"instance\":\"3\",\"value\":{\"value\":19.5,\"scale\":\"CELSIUS\"},\"timeOfSample\":\"2022-12-15T19:45:39Z\"}",
            "{\"namespace\":\"Alexa.EndpointHealth\",\"name\":\"connectivity\",\"instance\":\"10\",\"value\":{\"value\":\"OK\"},\"timeOfSample\":\"2022-12-15T19:45:39Z\"}",
            "{\"namespace\":\"Alexa.RangeController\",\"name\":\"rangeValue\",\"instance\":\"4\",\"value\":44.0,\"timeOfSample\":\"2022-12-15T19:45:39Z\"}",
            "{\"namespace\":\"Alexa.RangeController\",\"name\":\"rangeValue\",\"instance\":\"5\",\"value\":10.0,\"timeOfSample\":\"2022-12-15T19:45:39Z\"}",
            "{\"namespace\":\"Alexa.RangeController\",\"name\":\"rangeValue\",\"instance\":\"8\",\"value\":1.0,\"timeOfSample\":\"2022-12-15T19:45:39Z\"}",
            "{\"namespace\":\"Alexa.RangeController\",\"name\":\"rangeValue\",\"instance\":\"9\",\"value\":87.0,\"timeOfSample\":\"2022-12-15T19:45:34Z\"}",
            "{\"namespace\":\"Alexa.RangeController\",\"name\":\"rangeValue\",\"instance\":\"6\",\"value\":14.0,\"timeOfSample\":\"2022-12-15T19:45:39Z\"}"
         ],
         "error":"None"

My current method just hard codes this number to pull back the reading I want. I only have one air monitor  so I dont know if these instance numbers are always the same or if they could vary in different peoples setups. Either way its probably not great way to handle this. So I need to try and find a better way.

Not sure if anyone even reads this but would be happy for some input :)

**Comment by Snid0** [comment]
So I have managed to get it all working. Seems to be fairly reliable on my system. The one problem I am having is that it only updates around every 10 minutes. I have read that this is to do with websocket code that reduces the polling from the user specified interval by a factor of 10. I assume this is because the code is awaiting some responses on the websockets. Not really sure how to get around this. I guess an update every 10 mins isnt too bad for the type of data it is collecting.

**Comment by Snid0** [comment]
@sdaltons1 if you wanted to test it you could download from my fork

**Comment by alandtse** [comment]
> Thank you @Snid0 for your work on this!
> 
> @alandtse could we see about getting this added?

The way it works is someone submits a PR with the changes. I'll review the code changes for anything obvious and work with the person submitting it before we merge it in.

**Comment by Snid0** [comment]
> > Thank you @Snid0 for your work on this!
> > @alandtse could we see about getting this added?
> 
> The way it works is someone submits a PR with the changes. I'll review the code changes for anything obvious and work with the person submitting it before we merge it in.

Thanks Alan. I still need to tidy up my code a bit and will submit it for you to review soon.

**Comment by Snid0** [comment]
@alandtse Do you know why the update interval is reduced when websockets are enabled? Is it a requirement of the websocket functionality or just to reduce traffic to the amazon servers? Are websockets something the user can disable with config? 

I cant see any information in websocket pushed commands related to the air quality sensors. So the only time they get updated is when the system polls amazon, which seems to be 10 minutes.

**Comment by alandtse** [comment]
Reduce traffic so we don't get banned. It's a precaution since we're hacking an unofficial API.
