### ISSUE TITLE
Alexa Media Player 4.5 next timer, reminder, alarm unavailable

### ISSUE THREAD

**Issue by OwenBerg79** [custom-components/alexa_media_player#1824]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/custom-components/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

V4.5 has caused next_timer, next_alarm, next_reminder to report as unknown.
Further updates to these services are not reported back to the integration.

**To Reproduce**

1. Install V4.5
2. Set a timer on an echo device
3. Check for updated next_timer entity for that device 
4. Unknown reported as status. Status is unknown from the time of restart relating to upgrade to V4.5. Previous timers also missing from the entity.

**Expected behavior**

Next_timer, alarm, reminder would normally report a date time string of the next event. It would also report a string of previous events under the "Sorted All" attribute
**Screenshots**

Issue under V4.5:
![Screenshot_2023-01-13-08-44-54-64_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/103262484/212277577-0a59744a-9161-4ec0-995f-91f5070642b5.jpg)

Correct behaviour under V4.4:
![Screenshot_2023-01-13-08-49-26-98_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/103262484/212277850-641595e3-5f88-4304-b460-27fe83ee74b0.jpg)

**System details**

- Home-assistant (version): 2023.1.4
- alexa_media (version from `const.py` or HA startup): 4.5
- alexapy (version from `pip show alexapy` or HA startup):
- Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). : y

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

**Additional context**

**Comment by Puddingpanzer** [comment]
same here, thank you for adressing the issue again

**Comment by OwenBerg79** [comment]
I can't see any significant differences between the log files for V4.4 and V4.5 and I'm not entirely sure how far I need to go on censoring private information!

**Comment by hugalafutro** [comment]
I have the same issue, but I too am wary of providing logs as I do not know if they do not include any personally identifiable information. Sometimes GitHub devs really irk me off, like I understand the need for the template in some cases, but this issue is self explanatory - you update the thing and everything stops working and shows as Unknown.

So am I then to believe it 
a) worked for the dev only and not everyone else
b) dev doesn't actually use the integration ?

Otherwise why the need for logs, like I mean your logs must show the same as it doesn't work for nobody from what I gather? Pardon me if I'm wrong I'm not the most technical person.

**Comment by broyuken** [comment]
The dev for Alexa media player is extremely responsive and helpful. Give him a minute and he’ll get it working for you. He does this for free, get off his back. If you don’t like it then stop using this component and code your own.

**Comment by alandtse** [comment]
> Otherwise why the need for logs, like I mean your logs must show the same as it doesn't work for nobody from what I gather? Pardon me if I'm wrong I'm not the most technical person.

This attitude is the reason I don't really want to and bother to maintain this anymore. The code is open so hopefully someone else submits a PR to fix this by submitting a PR. You can always downgrade if it was working for you before. 

The logs are necessary for me to figure out why it's breaking on systems where it's breaking. You don't have to provide the logs if you don't feel comfortable but I don't have to fix it if I don't have the info.

> I can't see any significant differences between the log files for V4.4 and V4.5 and I'm not entirely sure how far I need to go on censoring private information!

For this I just need to see the error that is causing it to break. There will normally something about an "exception". Once I know what it looks like, then I can catch it and fix it.

> The dev for Alexa media player is extremely responsive and helpful. Give him a minute and he’ll get it working for you. He does this for free, get off his back. If you don’t like it then stop using this component and code your own.

Thanks for the support. But to be honest, as mentioned earlier, I'm not as active on this as before since it's more or less working for me but for people who are respectful I'm more inclined to resolve it.

**Comment by OwenBerg79** [comment]
Thanks, I didn't see any exceptions before, that's the sort of thing I was looking for.
I'll try going through it all again if I get time over this weekend though.
