### ISSUE TITLE
Alexa Next Alarm/Timer/Notification sensors create large entries in the database

### ISSUE THREAD

**Issue by monotonus** [custom-components/alexa_media_player#1845]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/custom-components/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

I observed that my home assistant sqlite DB was running bigger than before in the last days. Today I've searched for the biggest entities in my DB and found, that three sensor.*_next_alarm entities made 78 percent of my data in the tables states and state_attributes.

So I don't know if it's really a bug or intended behaviour, but 55 percent for one echo device is quite a lot. For now I excluded these entitites from being written into the HA DB.

Just wanted to let you guys know.

1. Open the DB with an SQLite explorer like "DB Browser for SQLite"
2. Run the following SQL:

SELECT
  COUNT(*) AS cnt,
  COUNT(*) * 100 / (SELECT COUNT(*) FROM states) AS cnt_pct,
  SUM(LENGTH(shared_attrs)) AS bytes,
  SUM((LENGTH(shared_attrs)) * 100) / (SELECT SUM(LENGTH(shared_attrs))  FROM state_attributes) AS bytes_pct,
  entity_id
FROM states, state_attributes
WHERE
  states.attributes_id = state_attributes.attributes_id
GROUP BY entity_id
ORDER BY bytes DESC

See: https://community.home-assistant.io/t/how-to-keep-your-recorder-database-size-under-control/295795/97 

**Expected behavior**

**Screenshots**

![screenshot](https://user-images.githubusercontent.com/51734505/214009111-53c7e8b2-de5c-4e85-9991-76b0b0b5eb12.jpg)

**System details**

- Home-assistant (version): 2023.1.5
- alexa_media (version from `const.py` or HA startup): v4.5.3
- alexapy (version from `pip show alexapy` or HA startup):
- Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). : yes

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

**Additional context**

**Comment by alandtse** [comment]
Thanks. It's because each alarm potentially has attributes with raw JSON data which is stored by the recorder. This can become huge becomes Alexa doesn't delete alarms but creates new ones. We might be able to put an option to only enable the attributes as an option so it doesn't impact most people.

Maybe someone can write a SQL query for the wiki to periodically flush this data out.

**Comment by alandtse** [comment]
So, given the latest version of HA will automatically ignore large attributes and pop a warning #1867, I'm going to close this because it's essentially downgraded from a bug and now is more of an enhancement. We probably still need a SQL query to help clean out old log data, but I'll leave it to the community to draft it.
