### ISSUE TITLE
API: Too Many Requests

### ISSUE THREAD

**Issue by Toukite** [custom-components/alexa_media_player#1894]
Hello,

I noticed recently that I have many errors in HA logs related to this integration, that were not present before this month.

For example:
-  Error fetching alexa_media data: Error communicating with API: Too Many Requests 
-  Giving up _static_request(...) after 5 tries (alexapy.errors.AlexapyTooManyRequestsError: Too Many Requests) 
-  alexaapi.get_entity_state((<alexapy.alexalogin.AlexaLogin object at yyy>,), {'entity_ids': ['xxx']}): An error occured accessing AlexaAPI: An exception of type AlexapyTooManyRequestsError occurred. Arguments: ('Too Many Requests',) 

My usage has not changed in the past months, I have everything up to date (Alexa Media Player v4.6.2,  Home Assistant 2023.3.6, Supervisor 2023.03.2, Operating System 9.5)

Is there anything I can do to solve this issue ?

Thank you for the help !

**Comment by Casadomoticap** [comment]
I have the same error in the LOGs, any help?

**Comment by Moxser** [comment]
Ho everyone. Same issue here.
I have had this error for a week

**Comment by mfabiani53** [comment]
Here it is my log full of these entries.... it seems the same as other users reported.

```
2023-03-28 22:15:40.308 ERROR (MainThread) [alexapy.alexaapi] Giving up _static_request(...) after 5 tries (alexapy.errors.AlexapyTooManyRequestsError: Too Many Requests)
2023-03-28 22:15:40.356 ERROR (MainThread) [custom_components.alexa_media] Error fetching 
```

**Comment by fherreror** [comment]
Same here. Also in Spain

**Comment by figorr** [comment]
> Same here. Also in Spain

Did you try the tts?

I just tried today under Node-Red and It is not working? I am receiving API Error at the “Call Service” node. But it was working ok at least until the last week.

**Comment by figorr** [comment]
I have just arrived at home and I tested tts and It seems it is working again. So .... it looks like a temporay Amazon Server Problem. Let's hope it is just temporary and it has been solved.

**Comment by yolani** [comment]
I habe the same issue in Germany, also the temperature sensor of my echo becomes unavailable all the time.

**Comment by fherreror** [comment]
In my case, the temperature sensor is also down. The rest of functionalities work fine. The only thing I have not working is temperature sensor.

**Comment by akula3** [comment]
Same here in Germany.
It is concerned to build-in temperature sensor in Echo4 and two light bulbs connected to the same Echo4.

**Comment by dpgh947** [comment]
I have been seeing this for the past few weeks too. Nothing seems to stop working as far as I can see, but the errors keep being logged.

**Comment by alandtse** [comment]
Please +1 instead of me too. This is Amazon's servers denying the request. Not much more we can do on this component. We already have minimized API calls, but will take PRs for further reduction if someone figures out what Amazon will tolerate now. Given Amazon is losing a lot of money with Alexa and Jeff Bezos is no longer supporting it, we're likely to see further restrictions.

**Comment by dpgh947** [comment]
What does the queue interval setting under "configure" do? I've tried it up to 5 but I can't see it having any effect on how things work or how spaced out the calls in the debug log are.

**Comment by alandtse** [comment]
> What does the queue interval setting under "configure" do? I've tried it up to 5 but I can't see it having any effect on how things work or how spaced out the calls in the debug log are.

When there's an opportunity to queue multiple requests as a single request with multiple steps. This sets how many seconds to wait for more before sending the request. This is only applicable for Alexa routines and steps that can be added to a routine and it wouldn't have anything to do with the error being reported.

**Comment by dpgh947** [comment]
> > What does the queue interval setting under "configure" do? I've tried it up to 5 but I can't see it having any effect on how things work or how spaced out the calls in the debug log are.
> 
> When there's an opportunity to queue multiple requests as a single request with multiple steps, this sets how many seconds to wait for more before sending the request. This is only applicable for Alexa routines and steps that can be added to a routine and it wouldn't have anything to do with the error being reported.

Ok thanks.

**Comment by dpgh947** [comment]
There's something very odd going on here.... A few weeks ago I started getting 3 separate problems around the same time (I can't pin down exactly when or what update started them), all of which have open issues reported by many people - this "too many requests" problem, which doesn't seem to actually cause any loss of function, the Tuya "not updating status" problem  which does not record anything in the logs when it breaks, and which a reload fixes, and also the Localtuya problem of "Command 9 timed out/Disconnected waiting for discovery broadcast" messages which sometimes causes localtuya to stop working, sometimes not, and again a reload fixes it.

I have had Tuya and Localtuya running together for months. I first tried out Localtuya to see if it would make motion controlled lights respond any faster (it didn't), and never fully converted all devices, but everything worked fine until recently.

I have a node red flow to detect when Tuya breaks and reload it, and with that in place I found that Tuya was far more reliable than Localtuya, so I temporarily deleted all my Localtuya devices and updated everything that was using them to go back to using the "proper" Tuya devices... since I did this, I am getting no Localtuya errors (obviously, because it has nothing to do), no more Too Many Requests errors from this API, not one (was getting several per day), and even my Tuya integration has only been reloaded once in the past day and a half since I removed the localtuya devices, whereas before that it was also breaking several times a day...
