### ISSUE TITLE
Login attempt or request with invalid authentication from ***.***.***.***

### ISSUE THREAD

**Issue by sammyke007** [custom-components/alexa_media_player#2061]
**Describe the bug**

Since the latest updates (v4.7.5 and v4.7.6) I keep getting errors in the log regarding this integration. Nothing else has changed (2FA and password is unchanged).

**To Reproduce**

None

**Expected behavior**

No error logs anymore

**Screenshots**

None

**System details**

- Home-assistant (version): 2023.10.1 (OS 10.5)
- alexa_media (version from `const.py` or HA startup): Not found
- alexapy (version from `pip show alexapy` or HA startup): Not found
- Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). : YES, always has been

**Logs**

Login attempt or request with invalid authentication from 40.113.118.83 (40.113.118.83). See the log for details.

==>

Logger: homeassistant.components.http.ban
Source: components/http/ban.py:129
Integration: HTTP (documentation, issues)
First occurred: 09:57:14 (9 occurrences)
Last logged: 13:13:00

Login attempt or request with invalid authentication from 20.229.51.198 (20.229.51.198). Requested URL: '/auth/alexamedia/proxy?config_flow_id=dabeadcbdeb79108be4a74a2a06c38ca&callback_url=https://***.***.be/auth/alexamedia/callback?flow_id=dabeadcbdeb79108be4a74a2a06c38ca'. (Go-http-client/1.1)
Login attempt or request with invalid authentication from 13.95.133.245 (13.95.133.245). Requested URL: '/auth/alexamedia/proxy?config_flow_id=dabeadcbdeb79108be4a74a2a06c38ca&callback_url=https://***.***.be/auth/alexamedia/callback?flow_id=dabeadcbdeb79108be4a74a2a06c38ca'. (Go-http-client/1.1)
Login attempt or request with invalid authentication from 40.113.118.83 (40.113.118.83). Requested URL: '/auth/alexamedia/proxy?config_flow_id=dabeadcbdeb79108be4a74a2a06c38ca&callback_url=https://***.***.be/auth/alexamedia/callback?flow_id=dabeadcbdeb79108be4a74a2a06c38ca'. (Go-http-client/1.1)

**Additional context**

After a day or three with the above errors popping up, I need to re-authenticate Alexa Media Player. I did this twice with correct password and correct 2FA, but to no avail.

**Comment by alandtse** [comment]
This is warning you that people are trying to login using the proxy url we've opened up. If you don't recognize those IPs you should consider preventing access to your HA instance as this shows your wide open to the internet and people are actively hitting you to try to login. This url is particularly dangerous to expose since it is logging into Amazon and could in theory have full access to your amazon account. This url is also unpublished and only open during a configuration attempt so it's a bit disconcerting people are finding it.

We have counter measures in place to only allow a known login from HA to use this URL but given how many IPs are hitting you, all it takes is one attacker getting through. Please note, due to a limitation from HA, we can't completely shutoff this auth path until the next restart.

**Comment by sammyke007** [comment]
Changing the accessible URL to the internal one (instead of the external / Cloudflare one) fixed it for me!
