### ISSUE TITLE
Each night the integration disconnect and ask for re-auth

### ISSUE THREAD

**Issue by PaulBiod** [custom-components/alexa_media_player#2065]
My alexa based automations stopped working almost each night, sometimes even after a HA reboot. It asks for re auth.

![image](https://github.com/custom-components/alexa_media_player/assets/28720176/799c6c73-59e2-4544-b501-dd1fcec4c58f)

- Home-assistant (version): last one
- alexa_media (version from `const.py` or HA startup): last one
- alexapy (version from `pip show alexapy` or HA startup): last one
- Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). : No

**Comment by Guenni75** [comment]
I have the same problem with 2FA.
When i try to configure again, it says "Invalid 2-factor key".

**Comment by twinkie0101** [comment]
Had same problem, but followed directions [here](https://github.com/custom-components/alexa_media_player/issues/2059#issuecomment-1750446717) and no longer having issue.

**Comment by hphde** [comment]
No matter what I do, it's not longer working for me with 4.7.7

**Comment by hphde** [comment]
OMG. I enabled debugging and it said
`[alexapy.alexalogin] Not logged in due to email mismatch to stored h************p@g*******m`
`[alexapy.alexalogin] Resetting Login for h************p@g*******m  - amazon.de`
Recognize the two spaces in front of the dash! Doing copy & paste of the email it added a space after the email address.
After removing the space the logon started working again. PHEW.
