### ISSUE TITLE
Formatting of scripts/automations with hassio

### ISSUE THREAD

**Issue by mattnewham** [custom-components/alexa_media_player#251]
Formatting examples on wiki dont work:

```
- id: alexatemplatetest
  alias: Alexa Template Test
  trigger:
  action:
  - service: notify.alexa_media
    data_template:
      data:
        type: announce
      target: 
        - media_player.office_echo
        - media_player.bedroom_echo
      message: 'sensor status is {{ states("sensor.unlock_status") }}'
```

```
    domain, service_name, service_data, blocking=blocking, context=context)
  File "/usr/src/homeassistant/homeassistant/core.py", line 1130, in async_call
    processed_data = handler.schema(service_data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 267, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 589, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 427, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: extra keys not allowed @ data['data_template']
```

**Comment by mattnewham** [comment]
Your issue is use of - before service.

This appears to cause the issue. Removing the - fixes

**Comment by alandtse** [comment]
Thanks.

You mentioned in #250 that the second nested `data` was causing errors in the gui editor. Are you saying that isn't an issue anymore?

The error from voluptuous is saying whatever the defined schema in the gui editor rejects multiple keys. This is still valid syntax if you edit automation.yaml, but is a bug in HA's gui editor. The bug would have to be fixed in HA to allow multiple keys for target. If you see a way for us to override the voluptuous schema in the GUI editor via some sort of file, then we could try to fix it that way here.

**Comment by mattnewham** [comment]
Hey

This was editing the file directly. Error was thrown when reloading HA or
reloading automations from the GUI under config/system

With the automation setup with the hyphen in front of service (manually
editing the file) it appears in the gui automations list under config, but
clicking on it takes you to an empty page (suggesting it can’t render it).

Removing the hyphen shows the same behaviour, however the automation loads
successfully and will execute correctly.

It looks like maybe automations in hassio must validate through the GUI
otherwise they won’t work at all?

**Comment by alandtse** [comment]
Ok make ssense.

As for the validation question, that would be new behavior I think if hassio forced a validation prior to running. 

As much as I don't like directing you to HA, the immediate issue appears related to how HA handles automations in hassio whether it's doing some sort of forced validation or not parsing the nested `data` tag in the gui. In the short term, I'm not planning to look at submitting changes to HA to support our non-standard calls. It's possible you could flag the issues there in a more generic way and someone could pick it up in that repo.

Yes, we could try to standardize our API call to something HA uses, but one reason we haven't [officially submitted](https://github.com/keatontaylor/alexa_media_player/issues/182) is we had to create non standard calls for some of our functionality.  Frankly, I haven't been focusing my time on submission because there are other features outstanding and HA's submission process is a bit heavier. 
 
That said, @keatontaylor was looking at some rewrites to get us async which takes us closer to our goals for HA, but we don't have a timeline.

We can leave this open if you'd like to see if someone wants to see if they can handle it.

**Comment by mattnewham** [comment]
Hey

That’s cool - I will submit an issue to HA to check that there’s not
something like changing the formatting to get it to work.

If we keep this issue open I’ll update it with any info I get from the HA
side and then maybe we just need to update the wiki to reflect how to
format the automations/scripts.

This appears to only be an issue with multiple nested data fields.

I do think this would have a lot of uptake if it was submitted as I’ve been
using Sonos announcements for a long time now, but echo announcements would
be way more appropriate in my environment.

**Comment by alandtse** [comment]
One workaround for the multiple target keys may be to use either Alexa or HA groups. The service will expand to the actual entities.

**Comment by alandtse** [comment]
Closing stale issue.
