### ISSUE TITLE
No function of start / stop / pause

### ISSUE THREAD

**Issue by funkschrauber** [custom-components/alexa_media_player#421]
**Describe the bug**
No function of start / stop / pause via media control or automation

**To Reproduce**
1. media control
2. Click on Pause
3. no function

**Expected behavior**
The echo can not be controlled via the Media Control or via automation. Applies to Play / Pause / Stop. Volume works.

**Screenshots**

**System details**
    Home-assistant (version): 0.99.3
    Hassio (Yes/No): YES
    alexa_media (version from const.py or HA startup): 2.3.1
    alexapy (version from pip show alexapy or HA startup): 1.3.2

**Logs**
[halog.txt](https://github.com/custom-components/alexa_media_player/files/3707043/halog.txt)

**Comment by Dielee** [comment]
![ha](https://user-images.githubusercontent.com/45101649/66480614-5f3c5580-ea9f-11e9-813b-3d9bfb516796.gif)

**Comment by alandtse** [comment]
First, the `media_player.media_stop` service should have never worked and actually is a bug because there's no function in the media player. The only options should be play and pause.

The logs are not showing any errors with the calls and the fact the volume control works shows we're connected.

Please test the following using the Developer tools and without any automations/scripts. I will only need the logs showing the part here and please try to identify where in the logs each part starts.
* Identify the specific HA state being reported. Is it standby or paused, etc?
* Attempt to play something from Amazon Music. Show the json data and specific service call. This should be `media_player.play_media`
* Attempt play and pause using the service call `media_player.media_play_pause`, `media_player.media_play`, or `media_player.media_pause` 
* Use your voice to start the device. See if HA reports any state changes.
* Try to pause the service.
* Conduct the same tests above using the Alexa app.

**Comment by Dielee** [comment]
The state change seems not to be reported.
I see the following status changes: 
```
PUSH_ACTIVITY
PUSH_VOLUME_CHANGE
PUSH_EQUALIZER_STATE_CHANGE
PUSH_MEDIA_QUEUE_CHANGE
```
Playing amazon music gave me the same error as TuneIn.
Amazon music play and pause logs are here: https://cloud.linusdietz.eu/index.php/s/vkUlGx6ubFRxlUu

Using the voice and app results in the same error.
Log from this are here: https://cloud.linusdietz.eu/index.php/s/55zUjgG5qqjajlC

**Comment by alandtse** [comment]
@Dielee For this thread on the play/pause functions, can you report on whether service calls to play and pause worked vs the app commands? The service_call logs are still showing Status 200 which means Amazon accepted the command.

**Comment by Dielee** [comment]
I helped @alandtse with debugging. 
Currently it seems HA is not getting PUSH_MEDIA_CHANGE 
and therefore the status is not updated.
A quickfix for the error is attached.

[media_player.zip](https://github.com/custom-components/alexa_media_player/files/3716589/media_player.zip)

Download the file and replace it with the one in the alexa_media folder.

**Comment by northpower25** [comment]
Great this works for me (Germany)

**Comment by funkschrauber** [comment]
Works only with stations running on Tune IN. And the status is not displayed directly updated. Only when you give the echo again a command.

Funktioniert aber nur mit Sendern, die über Tune IN laufen. Und der Status nicht direkt aktualisiert angezeigt. Erst wenn man dem Echo erneut  einen Befehl gibt.

**Comment by alandtse** [comment]
Please focus on the play and pause topic. I will be marking the rest off topic.

**Comment by northpower25** [comment]
with the fix from @Dielee [media_player.zip](https://github.com/custom-components/alexa_media_player/files/3716589/media_player.zip) from yesterday it works for TuneIn but with the new Version v2.3.2 from HACS it dosn't work.

**Comment by alandtse** [comment]
@northpower25 when you say works, are you referring to the play/pause command or to the state update? If it's the state update, please report it in #397 moving forward.

**Comment by alandtse** [comment]
Please try 2.3.3 and reopen if issue still exists.

**Comment by funkschrauber** [comment]
This works.
Perfect.

**Comment by northpower25** [comment]
It works now with TuneIn and Amazon Music
