### ISSUE TITLE
album art not showing when playing from pandora

### ISSUE THREAD

**Issue by randyarrasmith** [custom-components/alexa_media_player#582]
Album art not showing when playing from pandora.
(aside:  The mini-media-player does show art)

Looking at the web inspector it appears the album art is coming from https://dyn-images.p-cdn.com.

When playing music from amazon and not pandora album art works fine.  The background image url / entity_picture is  https://m.media-amazon.com

While troubleshooting I have updated this component, reinstalled the component and also update to latest HA version.

**System details**
 - Home-assistant (version):  0.106.5
 - HA from dockerhub
 - alexa_media  (version HACS): v2.5.6
 - alexapy (version from `pip show alexapy` or HA startup):  1.5.1

**Comment by alandtse** [comment]
Can you provide the attributes for the media player while playing Pandora?  Also, if you use the [webapp](alexa.amazon.com), does it show album art?

**Comment by randyarrasmith** [comment]
Sorry, I thought I had provided the platforms I tested in; I have tested in Safari(mac), Chrome(mac), and the HA iOS app.
I have alexa_media_player installed via hacs so no additional config there.
My lovelace config is: 
`- entity: media_player.office
     type: media-control`

**Comment by alandtse** [comment]
Ok, I was able to confirm it. However, if the entity_picture attribute is populating, then it's up the HA UI to figure out how to display it. 

The custom_component won't be able to change anything that the UI does. If you see a use case where the entity_picture is not being populated, then we may be able to do something on the component side. We are literally providing the information from the Alexa media API which is successfully displayed by Amazon UI elements and the mini-media-player.  It's also possible that Pandora is passing back an invalid URL and the UI team will say it's the components job to catch bad data from the API. I don't think that's the right response to this but may consider that.

While I don't know the specifics of the UI, it's probably because of the `)` after cover not being [escaped](https://stackoverflow.com/questions/25613552/how-should-i-escape-image-urls-for-css) in the url for the back-image css styling.

This is what I see in chrome.
```html
<div class="image" style="background-image: url(https://dyn-images.p-cdn.com/?l=images%2Fpublic%2Fint%2F0%2F8%2F9%2F4%2F00602577464980%3Acover()&amp;w=500&amp;h=500)"></div>
```
You'll need to report it to the HA UI team and point out that mini-media-player properly handles it. 
 Of course, if you tell them it's from a custom component they may say they won't fix it.

**Comment by alandtse** [comment]
By the way, I have a fix, but HA should really fix it in their own code or any other media player may have the problem and they should guard their own input.

**Comment by randyarrasmith** [comment]
Thank you, Alan.  I appreciate you looking into this.  I love the Alexa_media_player integration.  Glad you were able to find a workaround :)  You guys are awesome
