### ISSUE TITLE
Bug on an example on the wiki

### ISSUE THREAD

**Issue by paoloantinori** [custom-components/alexa_media_player#770]
**Describe the bug**
Before trying to modify this by myself, I'd like a second pair of eyes to validate this

This is not specific of `alexa_media_player` but if user copy paste the example, it will fail in a time wasting manner.

In the section `Live Sensor Report`, https://github.com/custom-components/alexa_media_player/wiki/Examples%3A-Automation#live-sensor-reports

the logic to convert the `light.alexa_virtual` is bugged.

It says:

`if (states.light.alexa_virtual.attributes.brightness | int / 255 * 100 ) | round  == 1`

but this was leading to wrong behavior.

In my case, when I've set the percentage on `1%` on an Alexa Routine, this was sending the value `4` to as the requested brigtness value.

If you debug the result of the above expression:
`(states.light.alexa_virtual.attributes.brightness | int / 255 * 100 ) | round` when the input value is `4` it produces `2` as the final output. The expected value should be `1`.

The reason for this is that `1.5686274509803921 | round` returns `2`.

To produce the correct answer, a different filter should be used:

` | int `

I'm not sure if this is the result of recent changes but I'd suggest to mention this on the wiki, otherwise it might be hard to notice the problem (in particular if the logic was also providing a `if x== 2` branch.

My system versions:

```
config $ ha core info
arch: aarch64
audio_input: null
audio_output: null
boot: true
image: homeassistant/raspberrypi4-64-homeassistant
ip_address: 172.30.32.1
last_version: 0.110.5
machine: raspberrypi4-64
port: 8123
ssl: false
version: 0.110.5
version_latest: 0.110.5
wait_boot: 600
watchdog: true
```

**Comment by alandtse** [comment]
I'm not sure who added that to the wiki, but you could check the history for the old [page](https://github.com/custom-components/alexa_media_player/wiki/Automation-examples/_history) to see. I think the person who did it may have posted that example initially on the forums so you might be able to find the thread there and message them.

You could just change the example if you've tested it. Since it has reversion history, someone could also look up the history (you may want to have an informative commit message) to then message you.

**Comment by paoloantinori** [comment]
Done, thank you!
