### ISSUE TITLE
Repeat sound

### ISSUE THREAD

**Issue by poudenes** [custom-components/alexa_media_player#845]
Hi All,

Love the script and how far developers are with implementation of Alexa into HA!!!
Is there a way to repeat a sound until there will be send a stop signal?

I want use Alexa to repeat a alarm sound... and when I hit a button (in ha) it will send a stop signal.

cheers

**Comment by alandtse** [comment]
Probably not as I don't think the app allows it. Questions like this are probably best asked on the forum since that has higher traffic; GitHub is best for technical issues.  Perhaps someone has an automation that does what you want. I'll leave this open for a week to see if anyone else chimes in, but will close it after that point.

**Comment by poudenes** [comment]
THank you for the answer and true maybe on forum someone has build a solution.
