### ISSUE TITLE
\n in localized strings not rendering on 2FA popup

### ISSUE THREAD

**Issue by chemelli74** [custom-components/alexa_media_player#909]
**Describe the bug**
Small bug in the message layout below

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/57354320/92330950-291ea180-f073-11ea-8a75-12be62f4a36d.png)

**System details**
 - Home-assistant (version):  0.114.3
 - Hassio (Yes/No): No
 - alexa_media  (version from `const.py` or HA startup): v2.11.0
 - alexapy (version from `pip show alexapy` or HA startup):
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) : yes

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

**Additional context**

**Comment by alandtse** [comment]
It's likely due to the language translations and the \n not being recognized in the international string. You can modify the it.json string to see what we can use as a line break in the translated files. Any changes to translations files requires a hard refresh of your browser to avoid the cached copy. If you'd like to [join](https://github.com/custom-components/alexa_media_player/wiki/Translations) the translation team you can then make the change for the next release.
