### ISSUE TITLE
Sending audio from new media browser to Alexa Media Player

### ISSUE THREAD

**Issue by daveonkels** [custom-components/alexa_media_player#940]
Does anyone have an example card/automation showing how to use the new HA [Media Browser](https://www.home-assistant.io/blog/2020/09/17/release-115/#media-browser) feature announced in 0.115 to direct the chosen content item on Alexa Media Player? I'm looking to add a Spotify card that has the option to direct the audio to one or more Alexa speakers.

![Screen Shot 2020-09-20 at 5 37 59 PM](https://user-images.githubusercontent.com/533642/93725956-2c805580-fb68-11ea-9c54-470230c9fc3b.png)

**Comment by alandtse** [comment]
AMP is required to go through Amazon for all content. So that means it has to go through an appropriate Amazon skill. Unless the other media browsers provide the content in that form, then no, the component won't be able to use the media browser. If you can identify some technical documents including pointing to the source code on how the stream passing is implemented, then we can take a look.

**Comment by freekeys** [comment]
This would be such a game changer!

**Comment by niemyjski** [comment]
Bump
