### ISSUE TITLE
Stuck in Verification Code Loop - Amazon requests credit card details to verify

### ISSUE THREAD

**Issue by scstraus** [custom-components/alexa_media_player#943]
**Describe the bug**
It keeps asking for a verification code, I keep answering, and it keeps asking again.

**To Reproduce**
1)Click notification, click button to login
2)Click notification, enter login code
3)GOTO 2

**Expected behavior**
Access to alexa media

**Screenshots**

**System details**
There's another similar bug from me with these details if you ened them. 

**Logs**
I'm going to send them to you by PM on the homeassistant board.

**Comment by alandtse** [comment]
Please fill out the template completely.

**Comment by alandtse** [comment]
Your logs indicate that it's asking for credit card information now to verify your identity (specifically expiration dates). I'm not sure if I want the component to ask for this type of information since it's going to end up with users thinking I'm harvesting their details. I'll think about it more. The easier solution is to make sure we don't end up in this state but your logs only start after this verification state was requested. Were there any other steps before?

Do you have 2FA already enabled?

**Comment by scstraus** [comment]
Honestly, the solution I would like the most would be if the component didn't bother trying to incorporate all this into the notification, but rather would just open a web page where we can interact with the real interrogation that's coming from Amazon.

**Comment by alandtse** [comment]
It's not possible to do it with a webpage unless you want to manually copy cookies from the browser for the component. 2FA is required to use the component. I am soliciting whether we'll fix this page since it will impact others, but otherwise I won't provide you any more support without 2FA because there are Javascript pages we can't get past because no one wanted to test it #807. Of course, you're welcome to submit a PR if you figure it out.

**Comment by scstraus** [comment]
I've updated the logs with some starting state from today at the top of the same text file I sent you the link to if it's interesting to you. 

But it sounds like 2FA is now a requirement for using the component, is that correct?

**Comment by alandtse** [comment]
[Yes](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account).

**Comment by stalakerob** [comment]
A clarifying question please: is the credit card verification now enabled by Amazon for all users?

**Comment by scstraus** [comment]
You know, I think all my problems in this and previous tickets I've opened link back to the issue described here:

https://community.home-assistant.io/t/alexa-media-player-as-integration-where-are-the-email-pass-stored/191501

Why is there nowhere to define the password any more?!??!?

**Comment by alandtse** [comment]
You just remove and readd the component to change the login info. HA doesn't provide any other mechanism. 

@stalakerob 
Given the only report of this problem is for someone without 2FA, it may only be a problem in that path. Again amazon throws a lot more verification to users without 2FA so that is why it's not supported.

**Comment by scstraus** [comment]
Okay, well we can close it. I went in and changed my password in .storage and enabled 2fa and now I'm back up and running.
